
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Movie extends ContentItem {
    public title: Elements.TextElement;
    public released: Elements.DateTimeElement;
    public releasecategory: Elements.TaxonomyElement;
    public seoname: Elements.UrlSlugElement;
    public length: Elements.NumberElement;
    public category: Elements.MultipleChoiceElement;
    public poster: Elements.AssetsElement;
    public stars: Elements.LinkedItemsElement<ContentItem>;
    public plot: Elements.RichTextElement;

    getCategoriesText(): string {
        if (!this.category) {
          return null;
        }
        return this.category.value.map(m => m.name.toLocaleLowerCase()).join(', ');
      }

      getStarsText(): string {
        if (!this.stars) {
          return null;
        }
        return this.stars.value.map(actor => actor.getFullName()).join(', ');
      }
}
